### ISSUE TITLE
AndroidUhidPureJava stops working in Android 14

### ISSUE THREAD

**Issue by huynhtanloc2612** [WuDi-ZhanShen/AndroidUHidPureJava#1]
Hi @WuDi-ZhanShen 
Thanks for sharing this code.
It works correctly in Android 13 and earlier Android version.
However, after I updated my phone to Android 14, it shows "Aborted" every time I try to run it.
I checked the Devices.java file in AOSP and see that there was no thing changes since 2022.
I am investigating the reason but have not found it.
Do you have any advice?
Thanks.

**Comment by WuDi-ZhanShen** [comment]
Thanks for your comment. I guess that the signature of the native method may changes in Android 14. I will fix it when I have free time.

**Comment by WuDi-ZhanShen** [comment]
> Hi @WuDi-ZhanShen Thanks for sharing this code. It works correctly in Android 13 and earlier Android version. However, after I updated my phone to Android 14, it shows "Aborted" every time I try to run it. I checked the Devices.java file in AOSP and see that there was no thing changes since 2022. I am investigating the reason but have not found it. Do you have any advice? Thanks.

Thanks for your comment. I guess that the signature of the native method may have changed in Android 14. I will fix it when I have free time.

**Comment by EDLLT** [comment]
> > Hi @WuDi-ZhanShen Thanks for sharing this code. It works correctly in Android 13 and earlier Android version. However, after I updated my phone to Android 14, it shows "Aborted" every time I try to run it. I checked the Devices.java file in AOSP and see that there was no thing changes since 2022. I am investigating the reason but have not found it. Do you have any advice? Thanks.
> 
> Thanks for your comment. I guess that the signature of the native method may have changed in Android 14. I will fix it when I have free time.

I also keep on getting Aborted on Android 12. I'm using a Samsung device(Samsung Galaxy S20 FE 5G)
This is my first time trying it

**Comment by EDLLT** [comment]
> > > Hi @WuDi-ZhanShen Thanks for sharing this code. It works correctly in Android 13 and earlier Android version. However, after I updated my phone to Android 14, it shows "Aborted" every time I try to run it. I checked the Devices.java file in AOSP and see that there was no thing changes since 2022. I am investigating the reason but have not found it. Do you have any advice? Thanks.
> > 
> > 
> > Thanks for your comment. I guess that the signature of the native method may have changed in Android 14. I will fix it when I have free time.
> 
> I also keep on getting Aborted on Android 12. I'm using a Samsung device(Samsung Galaxy S20 FE 5G) This is my first time trying 

Apparently the issue was with me getting into a shell session and trying to execute it from there(might be due to my environment as I have the systemless mkshrc magisk module installed)
Solution was to execute it via adb shell directly instead

`adb shell CLASSPATH="/data/local/tmp/Testing/virtual_hid_project/classes.dex" app_process / com.android.commands.hid.Hid`

🥹 been searching the whole internet for a way to create a virtual HID for a couple of years for my personal project with no success. istg as soon as I had given up and was closing my hundreds of tabs I stumbled upon this project

**Comment by lukas-schier** [comment]
> > Hi @WuDi-ZhanShen Thanks for sharing this code. It works correctly in Android 13 and earlier Android version. However, after I updated my phone to Android 14, it shows "Aborted" every time I try to run it. I checked the Devices.java file in AOSP and see that there was no thing changes since 2022. I am investigating the reason but have not found it. Do you have any advice? Thanks.
> 
> Thanks for your comment. I guess that the signature of the native method may have changed in Android 14. I will fix it when I have free time.

Any news or chance to get it working on Android 15? Which methods needs to be updated?
Would be awesome to use it with my Pixel 8

EDIT: I just updated [Device.java](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/cmds/hid/src/com/android/commands/hid/Device.java) from SDK35, added [SomeArgs.java](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/core/java/com/android/internal/os/SomeArgs.java), [UnsupportedAppUsage.java](https://android.googlesource.com/platform/prebuilts/fullsdk/sources/+/refs/heads/main/android-35/android/compat/annotation/UnsupportedAppUsage.java) and [RavenwoodKeepWholeClass.java](https://android.googlesource.com/platform//frameworks/base/+/5a11b433eeec86d58b2899a5e07d7facfec45d33/ravenwood/annotations-src/android/ravenwood/annotation/RavenwoodKeepWholeClass.java) files and set the new parameter 'uniq' in new Device(). Now it's working with Android 15. I am very bad in android development but maybe it's more useful to use the official NDK to support all SDK-Levels?

**Comment by WuDi-ZhanShen** [comment]
> > > Hi @WuDi-ZhanShen Thanks for sharing this code. It works correctly in Android 13 and earlier Android version. However, after I updated my phone to Android 14, it shows "Aborted" every time I try to run it. I checked the Devices.java file in AOSP and see that there was no thing changes since 2022. I am investigating the reason but have not found it. Do you have any advice? Thanks.
> > 
> > 
> > Thanks for your comment. I guess that the signature of the native method may have changed in Android 14. I will fix it when I have free time.
> 
> Any news or chance to get it working on Android 15? Which methods needs to be updated? Would be awesome to use it with my Pixel 8
> 
> EDIT: I just updated [Device.java](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/cmds/hid/src/com/android/commands/hid/Device.java) from SDK35, added [SomeArgs.java](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/core/java/com/android/internal/os/SomeArgs.java), [UnsupportedAppUsage.java](https://android.googlesource.com/platform/prebuilts/fullsdk/sources/+/refs/heads/main/android-35/android/compat/annotation/UnsupportedAppUsage.java) and [RavenwoodKeepWholeClass.java](https://android.googlesource.com/platform//frameworks/base/+/5a11b433eeec86d58b2899a5e07d7facfec45d33/ravenwood/annotations-src/android/ravenwood/annotation/RavenwoodKeepWholeClass.java) files and set the new parameter 'uniq' in new Device(). Now it's working with Android 15. I am very bad in android development but maybe it's more useful to use the official NDK to support all SDK-Levels?

The only thing we can do is to add new native method everytime when parameter changes. There is no way to support all SDK-Levels.

**Comment by WuDi-ZhanShen** [comment]
> > > Hi @WuDi-ZhanShen Thanks for sharing this code. It works correctly in Android 13 and earlier Android version. However, after I updated my phone to Android 14, it shows "Aborted" every time I try to run it. I checked the Devices.java file in AOSP and see that there was no thing changes since 2022. I am investigating the reason but have not found it. Do you have any advice? Thanks.
> > 
> > 
> > Thanks for your comment. I guess that the signature of the native method may have changed in Android 14. I will fix it when I have free time.
> 
> Any news or chance to get it working on Android 15? Which methods needs to be updated? Would be awesome to use it with my Pixel 8
> 
> EDIT: I just updated [Device.java](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/cmds/hid/src/com/android/commands/hid/Device.java) from SDK35, added [SomeArgs.java](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/core/java/com/android/internal/os/SomeArgs.java), [UnsupportedAppUsage.java](https://android.googlesource.com/platform/prebuilts/fullsdk/sources/+/refs/heads/main/android-35/android/compat/annotation/UnsupportedAppUsage.java) and [RavenwoodKeepWholeClass.java](https://android.googlesource.com/platform//frameworks/base/+/5a11b433eeec86d58b2899a5e07d7facfec45d33/ravenwood/annotations-src/android/ravenwood/annotation/RavenwoodKeepWholeClass.java) files and set the new parameter 'uniq' in new Device(). Now it's working with Android 15. I am very bad in android development but maybe it's more useful to use the official NDK to support all SDK-Levels?

I have updated the code to support Android 15. Try it?

**Comment by lukas-schier** [comment]
> > > > Hi @WuDi-ZhanShen Thanks for sharing this code. It works correctly in Android 13 and earlier Android version. However, after I updated my phone to Android 14, it shows "Aborted" every time I try to run it. I checked the Devices.java file in AOSP and see that there was no thing changes since 2022. I am investigating the reason but have not found it. Do you have any advice? Thanks.
> > > 
> > > 
> > > Thanks for your comment. I guess that the signature of the native method may have changed in Android 14. I will fix it when I have free time.
> > 
> > 
> > Any news or chance to get it working on Android 15? Which methods needs to be updated? Would be awesome to use it with my Pixel 8
> > EDIT: I just updated [Device.java](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/cmds/hid/src/com/android/commands/hid/Device.java) from SDK35, added [SomeArgs.java](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/core/java/com/android/internal/os/SomeArgs.java), [UnsupportedAppUsage.java](https://android.googlesource.com/platform/prebuilts/fullsdk/sources/+/refs/heads/main/android-35/android/compat/annotation/UnsupportedAppUsage.java) and [RavenwoodKeepWholeClass.java](https://android.googlesource.com/platform//frameworks/base/+/5a11b433eeec86d58b2899a5e07d7facfec45d33/ravenwood/annotations-src/android/ravenwood/annotation/RavenwoodKeepWholeClass.java) files and set the new parameter 'uniq' in new Device(). Now it's working with Android 15. I am very bad in android development but maybe it's more useful to use the official NDK to support all SDK-Levels?
> 
> I have updated the code to support Android 15. Try it?

I'm still getting the 'aborted' message with your updated code. But the solution from my first comment (edit) is working fine :)

**Comment by WuDi-ZhanShen** [comment]
> > > > > Hi @WuDi-ZhanShen Thanks for sharing this code. It works correctly in Android 13 and earlier Android version. However, after I updated my phone to Android 14, it shows "Aborted" every time I try to run it. I checked the Devices.java file in AOSP and see that there was no thing changes since 2022. I am investigating the reason but have not found it. Do you have any advice? Thanks.
> > > > 
> > > > 
> > > > Thanks for your comment. I guess that the signature of the native method may have changed in Android 14. I will fix it when I have free time.
> > > 
> > > 
> > > Any news or chance to get it working on Android 15? Which methods needs to be updated? Would be awesome to use it with my Pixel 8
> > > EDIT: I just updated [Device.java](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/cmds/hid/src/com/android/commands/hid/Device.java) from SDK35, added [SomeArgs.java](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/core/java/com/android/internal/os/SomeArgs.java), [UnsupportedAppUsage.java](https://android.googlesource.com/platform/prebuilts/fullsdk/sources/+/refs/heads/main/android-35/android/compat/annotation/UnsupportedAppUsage.java) and [RavenwoodKeepWholeClass.java](https://android.googlesource.com/platform//frameworks/base/+/5a11b433eeec86d58b2899a5e07d7facfec45d33/ravenwood/annotations-src/android/ravenwood/annotation/RavenwoodKeepWholeClass.java) files and set the new parameter 'uniq' in new Device(). Now it's working with Android 15. I am very bad in android development but maybe it's more useful to use the official NDK to support all SDK-Levels?
> > 
> > 
> > I have updated the code to support Android 15. Try it?
> 
> I'm still getting the 'aborted' message with your updated code. But the solution from my first comment (edit) is working fine :)

Sorry, I have uploaded the correct code. Try it!

**Comment by lukas-schier** [comment]
Working fine now! Thanks :)
